### ISSUE TITLE
Gatsby build error

### ISSUE THREAD

**Issue by imskr** [f0rr0/f0rr0.github.io#6]
* running `gatsby build` gives import error

```
import generateFeed from './src/scripts/feed.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/skr/github/f0rr0.github.io/node_modules/gatsby/dist/utils/webpack.config.js:62:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/skr/github/f0rr0.github.io/node_modules/gatsby/dist/utils/build-css.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
/home/skr/github/f0rr0.github.io/gatsby-node.js:2
import generateFeed from './src/scripts/feed.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/skr/github/f0rr0.github.io/node_modules/gatsby/dist/utils/build-page/url-resolver.js:34:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/skr/github/f0rr0.github.io/node_modules/gatsby/dist/utils/build-page/path-resolver.js:16:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
Generating CSS
```

Node: v12+

**Comment by imskr** [comment]
Works Well:
`using node v6.0.0`
`npm run build` - to generate static.
